</main><footer><div class="footer-middle"><div class="container"><div class="row"><div class="col-md-4 col-xs-12"><div class="logo-head"><div id="ul-id-header-siteName2" spellcheck="false" class="ul-widget ul-widget-wysivig-header" data-controls="e" data-tag="span" data-widget="header"><div spellcheck="false"><div class="ul-header-editor clearfix ul-header-wrap" style="outline:0;word-wrap:break-word;margin:0 5px"><span class="ul-w-header-span h1" style="text-align:center"><span class="g-color-text-2">max</span><span class="g-color-text-3">IMKO</span></span></div></div></div></div><div id="ul-id-wysiwyg-footerabout" class="ul-widget ul-widget-wysivig" data-image="true" data-controls="e" data-widget="wysiwyg"><div class="ul-wysivig-editor clearfix" style="outline:0;word-wrap:break-word"><p><span class="g-color-text-2"><?php
 $randtext = random_int(0,9);$text = ''; switch ($randtext){
    case 0:
    $text = 'Благодарим Вас за визит. Надеемся что вы смогли найти все необходимое на страницах нашего сайта.😊';
    break;
    case 1:
    $text = 'На страницах нашего сайта представлен большой ассортимент необычных и оригинальных товаров.🎈';
    break;
    case 2:
    $text = 'Интернет-магазин подарков Maximko – это то самое место, где вы всегда найдете море подарков на любой вкус и к каждому торжественному случаю.✌';
    break;
    case 3:
    $text = 'Мы занимаемся не только тем, что готовим подарки, но и организовываем праздники.🎁';
    break;
    case 4:
    $text = 'Не знаете что подарить?<br> Воспользуйтесь <a href="/picking" title="Идеи для подарка" style="color: #0f7bff !important;">сервисом</a> для генерации подарков😉';
    break;
    case 5:
    $text = 'Корпоративы, свадьбы, новый год, день рождения-нам по плечу любая задача.✨';
    break;
    case 6:
    $text = 'Не знаете что подарить? Напишите нам и мы обязательно вам поможем✨';
    break;
    case 7:
    $text = 'У вас есть идеи по улучшению сайта? или хотите поделиться с нами своими идеями, то пишите нам, и мы обязательно к вам прислушаемся✌';
    break;
    case 8:
    $text = 'А вы знали что мы теперь в Алисе!<br>Для того чтобы вызвать нас, запустите Яндекс(бета) и скажите "запусти исланд гифт". Вместе мы делаем данный ресурс лучше!';
    break;
    default:
    $text = 'Не смогли ничего найти?😞<br>Напишите нам, мы обязательно поможем Вам😇';
    break;
}
$text .= '<br>Будем крайне благодарны если Вы поучаствуете в нашем <a href="/survey" title="Опрос" style="color: #0f7bff !important;">опросе</a>';
echo $text;?></span><br></p></div></div><div style="text-align:  center;"><img src="/logo_white.png" title="магазин подарков Maximko" alt="магазин подарков Maximko" style="width: 70%;"></div></div><div class="col-md-4 col-xs-12"><div id="ul-id-contacts-bottom" class="ul-widget ul-w-contacts" data-controls="e" data-widget="contacts"><div id="id-contacts-schema-item" class="ul-w-contacts-design1 ul-w-contacts-custom-design1" itemscope itemtype="http://schema.org/Organization"><meta itemprop="name" content="maxIMKO"><div class="ul-w-contacts-item"><div class="ul-w-contacts-list"><span class="ul-w-contacts-item-title h2">Контакты</span><ul><li class="ul-w-contacts-f-phone normal"><a id="ul-w-contacts-phoneLink" class="ul-w-contacts-phoneLink" href="tel:<?=$this->phone;?>"><span itemprop="telephone"><span role="phone"><?=$this->phone?></span></span></a></li><address style="margin: 0"><li class="ul-w-contacts-f-address normal" itemprop="address"><a href="https://yandex.by/maps/org/maximko/114106620082/?ncrnd=6640" title="<?=$this->address?>"><?=$this->address?></a></li></address><li class="ul-w-contacts-f-skype normal"><a href="skype://live:<?=$this->skype?>?chat"><?=$this->skype?></a></li><li class="ul-w-contacts-f-email normal"><a href="mailto:<?=$this->mail?>"><span itemprop="email"><?=$this->mail?></span></a></li></ul></div></div></div></div><div class="bot-social-bar"><div id="ul-id-social-bar2" class="ul-widget ul-w-social ul-w-social-design1 ul-w-social-custom-design1" data-controls="e" data-widget="social" style="text-align:left"><span class="ul-w-social-icons" style="display:inline-block"><span class="ul-w-social-item"><a href="https://vk.com/islandgift" class="ul-w-social-icon ul-w-social-vkontakte ul-w-social-icon-active" target="_blank"></a></span><span class="ul-w-social-item"> <a href="http://t.me/max36895" class="ul-w-social-icon ul-w-social-telegram ul-w-social-icon-active" target="_blank"></a></span><span class="ul-w-social-item"><a href="skype://live:<?=$this->skype?>?chat" class="ul-w-social-icon ul-w-social-skype ul-w-social-icon-active" target="_blank"></a></span><span class="ul-w-social-item"><a href="https://api.whatsapp.com/send?phone=79092813520" class="ul-w-social-icon ul-w-social-whatsapp ul-w-social-icon-active" target="_blank"></a></span></span></div>
<script src="//yastatic.net/es5-shims/0.0.2/es5-shims.min.js"></script><script src="//yastatic.net/share2/share.js"></script><p style="padding-bottom: 0; padding-top: 5px;"><span class="g-color-text-2">Поделиться в соц. сетях</span></p><div class="ya-share2" data-services="vkontakte,facebook,telegram,odnoklassniki,whatsapp,viber,skype,moimir" data-counter="" data-limit="5"></div>
</div></div><div class="col-md-4 col-xs-12"><div id="ul-id-feedBack-footerform" class="ul-widget ul-widget-feedBack clearfix default" data-controls="e" data-widget="feedBack"><form class="feedBack" method="post" role="form"><div class="ul-widget-feedBack-form-group ul-widget-feedBack-header has-feedback"><div class="ul-w-feedBack-editable h2" data-name="header.title">Связаться с нами</div></div><div class="ul-widget-feedBack-form-group has-feedback has-feedback"><div class="ul-w-feedBack-control-label ul-w-feedBack-editable normal" data-name="name.title">Имя</div><input class="ul-widget-feedBack-form-control normal" type="text" autocomplete="given-name" id="userName" name="name" placeholder="Имя" required> <span class="ul-widget-feedBack-form-control-feedback icon-content-special-required"></span></div><div class="ul-widget-feedBack-form-group has-feedback has-feedback"><div class="ul-w-feedBack-control-label"><label class="control-label normal">E-mail</label></div><input class="ul-widget-feedBack-form-control normal" autocomplete="email" type="email" id="userMail" name="email" required placeholder="E-mail"> <span class="ul-widget-feedBack-form-control-feedback icon-content-special-required"></span></div><div class="ul-widget-feedBack-form-group has-feedback"><div class="ul-w-feedBack-editable" data-name="message.title"><div class="ul-w-feedBack-control-label ul-editor-wrapper clearfix normal" spellcheck="false"> Сообщение</div></div><textarea class="ul-widget-feedBack-form-control normal" name="message" id="userMessage" rows="3" placeholder="Сообщение" required></textarea> <span class="ul-widget-feedBack-form-control-feedback icon-content-special-required"></span></div><div class="ul-w-feedBack-control-label ul-w-feedBack-control-helpBlock"><span id="helpBlock" class="help-block note"> <span class="icon-content-special-required"></span> Обязательные поля </span></div><a type="submit" id="sendReviews" style="cursor: pointer;" class="ul-w-button1 middle">Отправить</a></form></div></div></div></div></div>
<div class="footer-sub"><div class="container"><div class="pull-left"><div id="ul-id-wysiwyg-copyright1" class="ul-widget ul-widget-wysivig" data-image="" data-controls="e" data-widget="wysiwyg" data-animation-type="fade" data-was-animated="true"><div class="ul-wysivig-editor clearfix" style="outline:0;word-wrap:break-word"><p><span class="g-color-text-2">© <?php echo date('Y');?>&nbsp;</span><span><a rel="nofollow" target="_blank" href="https://vk.com/islandgift">MAX</a><a href="https://www.иннка.рф" target="_blank" class="g-color-text-3">IMKO</a></span></p></div></div></div><div class="pull-right"><div id="ul-id-wysiwyg-copyright2" class="ul-widget ul-widget-wysivig ul-scroll-animate" data-image="" data-controls="e" data-widget="wysiwyg" data-animation-type="fade" data-was-animated="true"><div class="ul-wysivig-editor clearfix" style="outline:0;word-wrap:break-word"><p><a rel="nofollow" href="/siteerror" title="Сообщить об ошибке на сайте">Нашли ошибку?<span class="g-color-text-3"> Сообщите нам</span></a></p></div></div></div></div></div>
</footer><div class="ul-col ul-absolute-widgets" style="text-align: center">
<!-- корзина --><div id="ul-id-cart-0" class="ul-widget ul-widget-cart" data-drop-position-fixed="true" data-widget="cart" data-position="top" data-party="right" data-controls="e" data-constructor="false" style="display:none"><div class="ul-widget-cart-wrapper g-theme-block-2 js-widget-cart-wrapper ul-widget-cart-wrapper-shadow"><div class="ul-widget-cart-wrapper-empty"><div class="ul-widget-cart-wrapper-empty-text normal"><span data-typedictionary="captionCartIsEmpty" style="font-weight:700">Корзина пуста</span></div><div class="ul-widget-cart-wrapper-empty-icon"><span class="icon-shop-cart"></span></div></div><div class="ul-widget-cart-wrapper-full js-widget-cart-wrapper-full"><div class="ul-widget-cart-wrapper-full-content"><div class="ul-widget-cart-wrapper-full-content-data"><div class="ul-widget-cart-wrapper-full-content-data-wrapInfo"><a href="/order" class="ul-widget-cart-wrapper-full-content-data-wrapInfo-count js-widget-cart-count normal" style="font-weight:700" id="countShop">0</a><a href="/order" class="ul-widget-cart-wrapper-full-content-data-wrapInfo-unitsName js-widget-cart-units-name normal" data-typedictionary="unitsName" style="font-weight:700"> шт. </a><span class="ul-widget-cart-wrapper-full-content-data-wrapInfo-divider normal" style="font-weight:700">/</span><a href="/order" class="ul-widget-cart-wrapper-full-content-data-wrapInfo-price js-widget-cart-price normal" style="font-weight:700"><span data-type="value" data-raw="0" id="price">0</span><span data-type="currency">руб.</span></a></div><div class="ul-widget-cart-wrapper-full-content-data-button"><a class="ul-widget-cart-wrapper-full-content-data-button-pay g-color-text-1 js-widget-cart-button-checkout note" target="_self" data-typedictionary="buttonCheckout" href="/order"> Оформить </a><span class="ul-widget-cart-wrapper-full-content-data-button-clear js-widget-cart-button-clear note" data-typedictionary="buttonClear" id="remove-order"> Очистить </span></div></div><a href="/order" style="cursor: pointer;" class="ul-widget-cart-wrapper-full-content-icon"><img class="icon-shop-cart g-color-text-1" src="/img/kor.png" alt="Корзина"></a></div></div></div></div>
<!-- приветствие --><div id="ul-id-hello" class="ul-widget ul-widget-cart" data-drop-position-fixed="true" data-widget="cart" data-position="top" data-party="right" data-controls="e" data-constructor="false" style="display:none; right: calc(50% - 224px);top:111px !important;"><div class="ul-widget-cart-wrapper g-theme-block-2 js-widget-cart-wrapper ul-widget-cart-wrapper-shadow" style="min-height: 75px"><div class="ul-widget-cart-wrapper-full js-widget-cart-wrapper-full"><div class="ul-widget-cart-wrapper-full-content"><div class="ul-widget-cart-wrapper-full-content-data" style=" text-align: center;"><div class="ul-widget-cart-wrapper-full-content-data-wrapInfo" style="padding: 0; margin-bottom: 0;"><span class="ul-widget-cart-wrapper-full-content-data-wrapInfo-count js-widget-cart-count normal" style="font-weight:700;white-space: normal;max-width: 100%;">Добро пожаловать в магазин подарков Maximko!😸<br>Хорошего Вам дня✌</span></div></div><div class="ul-widget-cart-wrapper-full-content-icon icon-hello"><span class="fa fa-angellist ul-w-icon-size-32 g-color-text-2" style="color: #8bc63e;"></span></div></div></div></div></div>
<!-- погода --><div id="ul-id-weather" class="ul-widget ul-widget-cart" data-drop-position-fixed="true" data-widget="cart" data-position="top" data-party="right" data-controls="e" data-constructor="false" style="display:none; left: 25px;max-width:320px;top:41px !important;"><div class="ul-widget-cart-wrapper g-theme-block-2 js-widget-cart-wrapper ul-widget-cart-wrapper-shadow" style="min-height: 75px"><div class="ul-widget-cart-wrapper-full js-widget-cart-wrapper-full"><div class="ul-widget-cart-wrapper-full-content"><div class="ul-widget-cart-wrapper-full-content-data" style=" text-align: center;"><div class="ul-widget-cart-wrapper-full-content-data-wrapInfo" style="padding: 0; margin-bottom: 0;"><span class="ul-widget-cart-wrapper-full-content-data-wrapInfo-count js-widget-cart-count normal" style="font-weight:700;white-space: normal;max-width: 100%;" id="weatherText"></span></div></div></div></div></div></div>
</div><div class="modal-overlay closed" id="modal-overlay"></div><div class="modal closed" id="modal_form"  aria-hidden="true" aria-labelledby="modalTitle" aria-describedby="modalDescription" role="dialog"><div class="closeModal" id="close-button" title="Закрыть окно"><i></i></div><div class="modal-guts" role="document"><div class="ul-header-editor clearfix ul-header-wrap" style="outline:0;word-wrap:break-word;margin:0 5px"><span class="ul-w-header-span h1" id="modalTitle" style="text-align:center;font-size: 42px !important;"></span></div><p><span class="g-color-text-2" id="messageForUser" style="text-align:center"></span></p></div></div><div id="overlay"></div></div></div></div>
<script src="/script/plugins/plugin.js"></script><script src="/script/main.js"></script><div id="upbutton-container" class="ul-upbutton"><div class="ul-upbutton-icon"></div></div><script src="/js/js.js"></script>
<!-- Yandex.Metrika --> <script type="text/javascript" > (function (d, w, c) { (w[c] = w[c] || []).push(function() { try { w.yaCounter47399530 = new Ya.Metrika2({ id:47399530, clickmap:true, trackLinks:true, accurateTrackBounce:true, webvisor:true, trackHash:true }); } catch(e) { } }); var n = d.getElementsByTagName("script")[0], s = d.createElement("script"), f = function () { n.parentNode.insertBefore(s, n); }; s.type = "text/javascript"; s.async = true; s.src = "https://mc.yandex.ru/metrika/tag.js"; if (w.opera == "[object Opera]") { d.addEventListener("DOMContentLoaded", f, false); } else { f(); } })(document, window, "yandex_metrika_callbacks2"); </script><!-- Google Analytics --><script async src="https://www.googletagmanager.com/gtag/js?id=UA-85624028-3"></script><script>  window.dataLayer = window.dataLayer || [];function gtag(){dataLayer.push(arguments);}gtag('js', new Date());gtag('config', 'UA-85624028-3');</script>
<script type="application/ld+json">{"@context": "http://schema.org","@type": "Person","name": "MaxImko","url": "https://www.islandgift.ru","sameAs": ["https://vk.com/islandgift","https://www.facebook.com/profile.php?id=100002437442878","https://www.instagram.com/strelocmax36895/","https://twitter.com/strelocmax36895","https://plus.google.com/111445575727611888467"]}</script>
</body></html>
